import { ResumeProfile } from '@/lib/profiles/types'

/**
 * Gaurav's resume layout.
 *
 * Sections run: Header/Contact, Skills, Work Experience, Education, Projects,
 * Awards/Certificates, Soft Skills. Work experience is a flat list of bullets
 * under each role — there are no client/project sub-headings inside it.
 *
 * The rule text below is carried over verbatim from the original single-resume
 * prompts, so behaviour for this resume is unchanged.
 */

const SECTION_RULES = `## SECTION-LEVEL RULES (these override everything else):

### SKILLS section:
- You may REORDER existing skills to prioritize JD-relevant ones at the front of each list.
- You may REPLACE less-relevant skills with JD-critical skills. Be AGGRESSIVE here — if the JD requires a skill and the resume has a weaker/older alternative, SWAP IT. For example: "jQuery" → "React.js", "Jenkins" → "GitHub Actions", "MySQL" → "PostgreSQL".
- You CAN add JD-required skills even if not closely related, as long as they are in the same DOMAIN (e.g., adding a new framework the candidate could plausibly know).
- **CRITICAL CATEGORY MATCHING**: When replacing skills, you MUST respect the sub-category! If the JD requires a "Language" (e.g. Python, Java), you MUST place it in the line labeled "Languages:". If the JD requires a "Tool" (e.g. Docker, Git), you MUST place it in the line labeled "Tools:" or "Technologies:". NEVER put a framework in the languages line, or a language in the tools line.
- You MUST preserve the EXACT formatting structure. If the original has category labels like "Languages:" and "Technologies & Tools:", keep those exact category labels unchanged.
- Do NOT merge categories into one line. Do NOT split one category into multiple.
- Keep the same number of lines, the same pattern (label: comma-separated items).
- **KEEP THE LINE A SIMILAR LENGTH**: If swapping in JD skills makes the line noticeably longer, drop the LEAST relevant existing skills to make room. Aim to stay within about 20% of the original line length.

### WORK EXPERIENCE section:
- Company names, role titles, and date ranges are FROZEN — never modify them.
- ONLY modify the bullet-point descriptions of work done.
- **CRITICAL — ATS KEYWORD INJECTION**: For EVERY work experience role, you MUST rewrite at least 2 bullet points to DIRECTLY USE the JD's exact keywords, tool names, methodologies, and domain terms.
- Do NOT just "softly align" — REPLACE generic descriptions with JD-specific language. If the JD says "microservices architecture" and the bullet says "built backend modules", rewrite it to "architected microservices for backend systems".
- If the JD says "CI/CD pipelines" and the bullet says "automated deployment", rewrite to "implemented CI/CD pipelines for automated deployment".
- If the JD says "Agile/Scrum" and the bullet says "worked with team", rewrite to "collaborated in Agile sprints with cross-functional teams".
- The goal is that an ATS scanner reading each bullet point will find EXACT MATCHES for the JD's required skills.
- Preserve the core achievement and any metrics, but completely reframe the HOW using JD terminology.

### EDUCATION section:
- DO NOT modify anything. Skip this section entirely.

### PROJECTS section:
- Project names, links, and date ranges are FROZEN — never modify them.
- ONLY modify the project descriptions and bullet points.
- Apply the SAME aggressive keyword injection as work experience — rewrite bullets to use the JD's exact terminology.

### AWARDS / CERTIFICATES section:
- DO NOT modify anything. Skip this section entirely.

### SOFT SKILLS section:
- The soft skills use a Google Docs numbered list. The numbers (1. 2. 3.) are AUTO-GENERATED by the document — they are NOT part of the text content.
- In your "original" and "proposed" fields, include ONLY the skill text (e.g. "Communication Skills"), NEVER include the number prefix like "1." or "2.".
- You may replace soft skill names to better align with the JD, but keep the EXACT same count.
- Do NOT add bold, italic, or any formatting markers.
- Each replacement skill name should be similar in length to the original it replaces.

### HEADER / CONTACT section:
- DO NOT modify anything. Skip this section entirely.`

const REVAMP_SECTION_RULES = `## SECTION-LEVEL RULES (these override everything else):

### SKILLS section:
- You may REORDER existing skills to prioritize JD-relevant ones at the front of each list.
- You may REPLACE less-relevant skills with JD-critical skills. Be VERY AGGRESSIVE — swap out any skill the JD doesn't mention for one it explicitly requires.
- **KEEP THE LINE A SIMILAR LENGTH**: If swapping in JD skills makes the line longer, remove up to 5 of the LEAST relevant existing skills to make room. Aim to stay within about 20% of the original line length.
- **CRITICAL CATEGORY MATCHING**: Respect sub-categories. Languages go in "Languages:", frameworks in "Frameworks:", tools in "Tools:".
- Preserve the EXACT formatting structure (labels, comma-separated pattern, number of lines).
- Keep the total line length within about 20% of the original.

### WORK EXPERIENCE section:
- Company names, role titles, and date ranges are FROZEN — never modify them.
- ONLY modify the bullet-point descriptions of work done.
- **CRITICAL — ATS KEYWORD SATURATION**: For EVERY work experience role listed (not just the primary one), you MUST rewrite at least 2 bullet points to DIRECTLY USE the JD's exact keywords, tool names, methodologies, and domain terms.
- Do NOT "softly align" — COMPLETELY RESTRUCTURE bullet points around the JD's language.
- If the JD says "microservices" and the bullet says "built backend modules", rewrite to "architected and deployed microservices for backend systems".
- If the JD says "CI/CD with Jenkins" and the bullet says "automated deployment", rewrite to "implemented CI/CD pipelines using Jenkins for automated deployment".
- If the JD mentions "Agile/Scrum", "cross-functional teams", or "stakeholder management", weave these phrases into bullets.
- Keep the same achievement structure — if the original has a metric (e.g., "reduced load time by 40%"), preserve a similar metric.
- Keep the proposed text within about 30% of the original length.

### EDUCATION section:
- DO NOT modify anything. Skip this section entirely.

### PROJECTS section:
- **PROJECT TITLES, NAMES, LINKS, and HEADING LINES are FROZEN — NEVER modify them.**
- The first line of each project (the title/heading line, often containing project name, link, tech stack summary) is COMPLETELY FROZEN. Do NOT generate a change for it.
- ONLY modify the bullet-point descriptions UNDER each project heading.
- Apply the SAME aggressive ATS keyword injection — rewrite bullets to directly use JD terminology.
- Keep the proposed text within about 30% of the original length.

### AWARDS / CERTIFICATES section:
- DO NOT modify anything. Skip this section entirely.

### SOFT SKILLS section:
- The soft skills use a Google Docs numbered list. The numbers (1. 2. 3.) are AUTO-GENERATED — they are NOT part of the text content.
- In "original" and "proposed" fields, include ONLY the skill text (e.g. "Communication Skills"), NEVER include the number prefix.
- You may replace soft skill names to better align with the JD.
- Each replacement must be similar in character length to the original.

### HEADER / CONTACT section:
- DO NOT modify anything. Skip this section entirely.`

export const gauravProfile: ResumeProfile = {
  id: 'gaurav',
  label: 'Gaurav',
  personName: 'Gaurav Chaudhary',
  description: 'Flat bullets under each role; Projects section with numbered titles',
  defaultDocUrl: 'https://docs.google.com/document/d/1stlPithiuAkje-JK59M52ZOBQaPT2H5CiyeKZk_6-Ns/edit',
  urlStorageKey: 'resmod_resume_url',

  sectionRules: SECTION_RULES,
  revampSectionRules: REVAMP_SECTION_RULES,
  promptNotes: '',

  coverage: {
    frozenSection: /education|award|certificat|header|contact/i,
    experienceSection: /experience|employment|work history|professional background/i,
    projectSection: /project/i,
    minBulletLength: 40,
    frozenLinePatterns: [],
    // Two rewrites per section, or fewer if there aren't that many bullets.
    requiredChanges: (_section, bulletCount) => Math.min(2, bulletCount),
  },

  length: {
    maxGrowth: (len) => Math.max(50, Math.round(len * 0.6)),
    minLength: (len) => (len <= 25 ? 1 : Math.ceil(len * 0.6)),
  },
}
