/**
 * The house LaTeX template every resume is rendered into.
 *
 * It is the preamble the owner's hand-written resumes use, so an imported resume
 * typesets the same way and, more importantly, parses the same way: prose lives
 * in \resumeSummary, \skillLine and \resumeItem (editable), while employers,
 * roles, dates, project titles and client groups sit in structural macros that
 * lib/latex/parse.ts tags [Role], [Project] and [Group] and the tailoring passes
 * never rewrite.
 */
export const HOUSE_PREAMBLE = [
  '\\documentclass[letterpaper,11pt]{article}',
  '',
  '\\usepackage{latexsym}',
  '% T1 and a matching font give the PDF real glyph names, so ATS parsers read text.',
  '\\usepackage[T1]{fontenc}',
  '\\usepackage{lmodern}',
  '\\usepackage[empty]{fullpage}',
  '\\usepackage{titlesec}',
  '\\usepackage[usenames,dvipsnames]{color}',
  '\\usepackage{verbatim}',
  '\\usepackage{enumitem}',
  '\\usepackage[hidelinks]{hyperref}',
  '\\usepackage{fancyhdr}',
  '\\usepackage[english]{babel}',
  '\\usepackage{tabularx}',
  '\\input{glyphtounicode}',
  '',
  '\\pagestyle{fancy}',
  '\\fancyhf{}',
  '\\fancyfoot{}',
  '\\renewcommand{\\headrulewidth}{0pt}',
  '\\renewcommand{\\footrulewidth}{0pt}',
  '',
  '% Narrow margins so bullets stay on one line',
  '\\addtolength{\\oddsidemargin}{-0.6in}',
  '\\addtolength{\\evensidemargin}{-0.6in}',
  '\\addtolength{\\textwidth}{1.19in}',
  '\\addtolength{\\topmargin}{-0.7in}',
  '\\addtolength{\\textheight}{1.4in}',
  '',
  '\\urlstyle{same}',
  '\\raggedbottom',
  '\\raggedright',
  '\\setlength{\\tabcolsep}{0in}',
  '',
  '\\titleformat{\\section}{',
  '  \\vspace{-4pt}\\scshape\\raggedright\\large',
  '}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]',
  '',
  '% Machine-readable text layer for ATS parsers. Do not remove.',
  '\\pdfgentounicode=1',
  '',
  '\\newcommand{\\resumeItem}[1]{',
  '  \\item\\small{',
  '    {#1 \\vspace{-2pt}}',
  '  }',
  '}',
  '',
  '\\newcommand{\\resumeSubheading}[4]{',
  '  \\vspace{-2pt}\\item',
  '    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}',
  '      \\textbf{#1} & #2 \\\\',
  '      \\textit{\\small#3} & \\textit{\\small #4} \\\\',
  '    \\end{tabular*}\\vspace{-7pt}',
  '}',
  '',
  '\\newcommand{\\resumeProjectHeading}[2]{',
  '    \\item',
  '    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}',
  '      \\small#1 & #2 \\\\',
  '    \\end{tabular*}\\vspace{-7pt}',
  '}',
  '',
  '% A client engagement inside one employer',
  '\\newcommand{\\resumeGroupHeading}[1]{\\item[]\\small{\\textbf{#1}}\\vspace{-4pt}}',
  '',
  '\\newcommand{\\resumeSummary}[1]{{\\small #1}\\vspace{-4pt}}',
  '\\newcommand{\\skillLine}[1]{\\item\\small{#1}\\vspace{-4pt}}',
  '',
  '\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}',
  '',
  '\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}',
  '\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}',
  '\\newcommand{\\resumeItemListStart}{\\begin{itemize}}',
  '\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}',
  '\\newcommand{\\resumeSkillListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}',
  '\\newcommand{\\resumeSkillListEnd}{\\end{itemize}\\vspace{-6pt}}',
].join('\n')
