import Link from 'next/link'
import PolicyPage, { PolicySection } from '@/components/PolicyPage'

export const metadata = {
  title: 'Terms of Service | Chills',
}

export default function TermsOfService() {
  return (
    <PolicyPage title="Terms of Service" updated="17 September 2026">
      <PolicySection title="1. Acceptance of Terms">
        <p>By accessing and using Chills, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not use our service.</p>
      </PolicySection>

      <PolicySection title="2. Description of Service">
        <p>Chills turns a resume you upload (PDF, Word, LaTeX or text) into a structured LaTeX resume, and tailors it to job descriptions with AI. The AI proposes changes, you approve or reject each one, and the approved changes go into a tailored copy you can download, typeset or open in Overleaf. Chills can also write a cover letter for a tailored copy, list the keywords a job description is screened for, and write emails to recruiters that you can send from your own mailbox. The AI requests run on Chills AI: a model from a third-party AI provider, chosen by Chills.</p>
      </PolicySection>

      <PolicySection title="3. User Responsibilities">
        <ul className="list-disc pl-5 space-y-1">
          <li>You are responsible for maintaining the confidentiality of your Google account.</li>
          <li>You must only optimize resumes that you own or have explicit permission to modify.</li>
          <li>You are responsible for verifying that the tailored resume and any cover letter are truthful before you send them to an employer.</li>
          <li>You agree not to use the service for any illegal or unauthorized purpose.</li>
          <li>You agree not to get around usage limits, for example by using several accounts.</li>
        </ul>
      </PolicySection>

      <PolicySection title="4. AI-Generated Content">
        <p>The changes, cover letters and keyword lists Chills produces are generated by AI models from third-party providers. While we strive for high quality, we do not guarantee the accuracy, completeness, or effectiveness of the generated content. You are solely responsible for reviewing and approving any changes made to your resume, and for reading any cover letter, before using them in employment applications.</p>
      </PolicySection>

      <PolicySection title="5. Free Tailorings, Payments and Refunds">
        <ul className="list-disc pl-5 space-y-1">
          <li>Every account gets a number of free tailorings, once. They do not renew. After they are used, tailoring needs Pro or a credit pack, and either can be bought at any time.</li>
          <li>Pro is a monthly subscription with a number of tailorings each month. It renews automatically until you cancel it on the Plans page. Cancelling stops the next renewal; you keep Pro&apos;s tailorings until the end of the period you have already paid for. Tailorings left at the end of a month do not carry over.</li>
          <li>Credit packs are one-time purchases. Credits do not expire, and are used after Pro&apos;s tailorings and your free ones.</li>
          <li>A tailoring that fails without producing any changes is not counted.</li>
          <li>Payments are processed by Razorpay. Chills does not receive or store your card, UPI or bank details.</li>
          <li>If you are charged twice, or a purchase does not reach your account, the payment is refunded in full. An unused credit pack can be refunded within 7 days of purchase. A Pro payment for a billing period that has already started is not refunded.</li>
          <li>Prices are in Indian rupees and may change. A price change never affects a payment already made.</li>
        </ul>
        <p>Current prices are on the <Link href="/pricing" className="text-[var(--color-primary)] hover:underline">Pricing</Link> page, and the full details of cancelling and refunds are in the <Link href="/refunds" className="text-[var(--color-primary)] hover:underline">Cancellation and Refund Policy</Link>.</p>
      </PolicySection>

      <PolicySection title="6. Recruiter Emails">
        <ul className="list-disc pl-5 space-y-1">
          <li>Emails you send through Chills go out from your own mailbox, as you. You are responsible for what they say and for whom you send them to.</li>
          <li>Only email people you have a legitimate reason to contact about a job. Don&apos;t use Chills for marketing, bulk unsolicited email, or to contact anyone who has asked you not to.</li>
          <li>Read every email before you send it. The AI writes drafts from your resume, and you decide what is sent.</li>
          <li>Only connect a mailbox that is yours, with an app password you created for Chills.</li>
          <li>Each account can have the AI write a set number of recruiter emails a month and can send up to a daily limit, shown on the Pricing page. Chills may pause sending from an account that is used to send spam.</li>
          <li>Open tracking is approximate: some mail apps load images on their own, and others block them.</li>
        </ul>
      </PolicySection>

      <PolicySection title="7. Disclaimer of Warranties">
        <p>Chills is provided &quot;as is&quot; without any warranties, expressed or implied. We do not warrant that the service will be uninterrupted, secure, or error-free.</p>
      </PolicySection>

      <PolicySection title="8. Limitation of Liability">
        <p>In no event shall Chills or its developers be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the service, including but not limited to loss of employment opportunities or data loss.</p>
      </PolicySection>

      <PolicySection title="9. Contact">
        <p>For questions about these terms, a payment or a refund, see the <Link href="/contact" className="text-[var(--color-primary)] hover:underline">Contact</Link> page. How Chills handles your data is described in the <Link href="/privacy" className="text-[var(--color-primary)] hover:underline">Privacy Policy</Link>.</p>
      </PolicySection>
    </PolicyPage>
  )
}
