import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | ResMod',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[var(--color-bg)] py-12 px-6">
      <div className="max-w-3xl mx-auto space-y-8 text-[var(--color-text)]">
        <div className="space-y-2">
          <Link href="/" className="text-[var(--color-primary)] hover:underline text-sm font-medium">← Back to home</Link>
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="text-[var(--color-text-muted)]">Last updated: 16 September 2026</p>
        </div>

        <div className="space-y-6 text-sm leading-relaxed text-[var(--color-text-muted)]">
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">1. Acceptance of Terms</h2>
            <p>By accessing and using ResMod, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not use our service.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">2. Description of Service</h2>
            <p>ResMod turns a resume you upload (PDF, Word, LaTeX or text) into a structured LaTeX resume, and tailors it to job descriptions with AI. The AI proposes changes, you approve or reject each one, and the approved changes go into a tailored copy you can download, typeset or open in Overleaf. The AI requests run on ResMod AI: a model from a third-party AI provider, chosen by ResMod.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">3. User Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You are responsible for maintaining the confidentiality of your Google account.</li>
              <li>You must only optimize resumes that you own or have explicit permission to modify.</li>
              <li>You are responsible for verifying that the optimized resume remains truthful before you send it to an employer.</li>
              <li>You agree not to use the service for any illegal or unauthorized purpose.</li>
              <li>You agree not to get around usage limits, for example by using several accounts.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">4. AI-Generated Content</h2>
            <p>The changes ResMod proposes are generated by AI models from third-party providers. While we strive for high quality, we do not guarantee the accuracy, completeness, or effectiveness of the generated content. You are solely responsible for reviewing and approving any changes made to your resume before using it for employment applications.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">5. Free Tailorings, Payments and Refunds</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Every account gets a number of free tailorings, once. They do not renew. After they are used, tailoring needs Pro or a credit pack, and either can be bought at any time.</li>
              <li>Pro is a monthly subscription with a number of tailorings each month. It renews automatically until you cancel it on the Plans page. Cancelling stops the next renewal; you keep Pro&apos;s tailorings until the end of the period you have already paid for. Tailorings left at the end of a month do not carry over.</li>
              <li>Credit packs are one-time purchases. Credits do not expire, and are used after Pro&apos;s tailorings and your free ones.</li>
              <li>A tailoring that fails without producing any changes is not counted.</li>
              <li>Payments are processed by Razorpay. ResMod does not receive or store your card, UPI or bank details.</li>
              <li>If you are charged twice, or a purchase does not reach your account, the payment is refunded in full. An unused credit pack can be refunded within 7 days of purchase. A Pro payment for a billing period that has already started is not refunded.</li>
              <li>Prices are in Indian rupees and may change. A price change never affects a payment already made.</li>
            </ul>
            <p>Current prices are on the <Link href="/pricing" className="text-[var(--color-primary)] hover:underline">Pricing</Link> page, and the full details of cancelling and refunds are in the <Link href="/refunds" className="text-[var(--color-primary)] hover:underline">Cancellation and Refund Policy</Link>.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">6. Disclaimer of Warranties</h2>
            <p>ResMod is provided &quot;as is&quot; without any warranties, expressed or implied. We do not warrant that the service will be uninterrupted, secure, or error-free.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">7. Limitation of Liability</h2>
            <p>In no event shall ResMod or its developers be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the service, including but not limited to loss of employment opportunities or data loss.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">8. Contact</h2>
            <p>For questions about these terms, a payment or a refund, see the <Link href="/contact" className="text-[var(--color-primary)] hover:underline">Contact</Link> page. How ResMod handles your data is described in the <Link href="/privacy" className="text-[var(--color-primary)] hover:underline">Privacy Policy</Link>.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
