import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service | ResMod',
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[var(--color-bg)] py-12 px-6">
      <div className="max-w-3xl mx-auto space-y-8 text-[var(--color-text)]">
        <div className="space-y-2">
          <Link href="/" className="text-[var(--color-primary)] hover:underline text-sm font-medium">← Back to home</Link>
          <h1 className="text-3xl font-bold">Terms of Service</h1>
          <p className="text-[var(--color-text-muted)]">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <div className="space-y-6 text-sm leading-relaxed text-[var(--color-text-muted)]">
          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">1. Acceptance of Terms</h2>
            <p>By accessing and using ResMod, you agree to be bound by these Terms of Service. If you disagree with any part of these terms, you may not use our service.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">2. Description of Service</h2>
            <p>ResMod is an AI-powered resume optimization tool. It reads a LaTeX resume, sends it with your job description to an AI provider of your choosing, and writes the edits you approve into a tailored copy of that LaTeX for you to download or compile.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">3. User Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You are responsible for maintaining the confidentiality of your Google account.</li>
              <li>You must only optimize resumes that you own or have explicit permission to modify.</li>
              <li>You are responsible for verifying that the optimized resume remains truthful before you send it to an employer.</li>
              <li>You agree not to use the service for any illegal or unauthorized purpose.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">4. AI-Generated Content</h2>
            <p>The optimizations provided by ResMod are generated by Artificial Intelligence (Google Gemini). While we strive for high quality, we do not guarantee the accuracy, completeness, or effectiveness of the generated content. You are solely responsible for reviewing and approving any changes made to your resume before using it for employment applications.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">5. Included Runs, Payments and Refunds</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Every account gets a number of free tailoring runs on ResMod AI each month. Unused free runs do not carry over to the next month.</li>
              <li>Credit packs are one-time purchases. Credits do not expire, and are used after free runs and Pro runs.</li>
              <li>Pro is a monthly subscription that renews automatically until you cancel it on the billing page. Cancelling stops the next renewal; you keep Pro&apos;s runs until the end of the period you have already paid for.</li>
              <li>A run that fails without producing any changes is not counted. Runs that use your own AI provider key, or Puter, are never counted.</li>
              <li>Payments are processed by Razorpay. ResMod does not receive or store your card, UPI or bank details.</li>
              <li>If you are charged twice, or a purchase does not reach your account, the payment is refunded in full. An unused credit pack can be refunded within 7 days of purchase. A Pro payment for a billing period that has already started is not refunded.</li>
              <li>Prices are in Indian rupees and may change. A price change never affects a payment already made.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">6. Disclaimer of Warranties</h2>
            <p>ResMod is provided &quot;as is&quot; without any warranties, expressed or implied. We do not warrant that the service will be uninterrupted, secure, or error-free.</p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-semibold text-[var(--color-text)]">7. Limitation of Liability</h2>
            <p>In no event shall ResMod or its developers be liable for any indirect, incidental, special, or consequential damages arising out of or in connection with your use of the service, including but not limited to loss of employment opportunities or data loss.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
