import { ResumeDoc } from '@/lib/resume-doc'
import { escapeLatexText } from '@/lib/latex/sanitize'
import { HOUSE_PREAMBLE } from '@/lib/latex/template'

/**
 * Rendering a structured resume into the house LaTeX template.
 *
 * Every piece of user text goes through escapeLatexText, so the output never
 * contains markup the user wrote. The layout mirrors the owner's hand-written
 * resumes, which is what lets lib/latex/parse.ts find each bullet, skill line
 * and summary as an editable span and each employer, project and client group
 * as a frozen structural line.
 *
 * Empty parts are left out rather than rendered empty: an itemize with no \item
 * stops pdflatex outright.
 */

const e = escapeLatexText

const HEADER_COMMENT = [
  '%-------------------------------------------------------------------------------',
  '% Generated by ResMod. Editable text lives in \\resumeSummary, \\skillLine and',
  '% \\resumeItem; names, roles, dates and headings are structural.',
  '% Compile with pdfLaTeX.',
  '%-------------------------------------------------------------------------------',
].join('\n')

/**
 * A link target that is safe inside a macro argument, or null for anything that
 * isn't http(s) or mailto (javascript: and friends never become links).
 */
export function latexUrl(url: string): string | null {
  const trimmed = url.trim()
  if (!trimmed) return null

  let parsed: URL
  try {
    parsed = new URL(/^[a-z][a-z0-9+.-]*:/i.test(trimmed) ? trimmed : `https://${trimmed}`)
  } catch {
    return null
  }
  if (!['http:', 'https:', 'mailto:'].includes(parsed.protocol)) return null

  return parsed.href
    // Characters URL leaves alone but LaTeX would act on: percent-encode them...
    .replace(/[~^\\{}]/g, (ch) => '%' + ch.charCodeAt(0).toString(16).toUpperCase())
    // ...then escape what hyperref needs escaped inside another macro's argument.
    .replace(/[%#&_$]/g, (ch) => '\\' + ch)
}

function link(url: string, label: string): string {
  const target = latexUrl(url)
  return target ? `\\href{${target}}{${label}}` : label
}

function nonEmpty(values: string[]): string[] {
  return values.map((value) => value.trim()).filter(Boolean)
}

function itemList(items: string[]): string[] {
  if (items.length === 0) return []
  return ['      \\resumeItemListStart', ...items.map((item) => `        ${item}`), '      \\resumeItemListEnd']
}

function bulletItems(bullets: string[]): string[] {
  return nonEmpty(bullets).map((bullet) => `\\resumeItem{${e(bullet)}}`)
}

export function renderResumeLatex(doc: ResumeDoc): string {
  const out: string[] = [HEADER_COMMENT, HOUSE_PREAMBLE, '', '\\begin{document}', '']

  // ---- heading
  const contact: string[] = []
  if (doc.contact.phone) contact.push(e(doc.contact.phone))
  if (doc.contact.email) contact.push(link(`mailto:${doc.contact.email}`, e(doc.contact.email)))
  for (const item of doc.contact.links) {
    const label = item.label || item.url.replace(/^https?:\/\//i, '').replace(/\/$/, '')
    contact.push(link(item.url, e(label)))
  }
  if (doc.contact.location) contact.push(e(doc.contact.location))

  out.push('\\begin{center}')
  if (contact.length > 0) {
    out.push(`    {\\Huge \\scshape ${e(doc.name)}} \\\\ \\vspace{3pt}`, '    \\small')
    out.push('    ' + contact.join(' $|$\n    '))
  } else {
    out.push(`    {\\Huge \\scshape ${e(doc.name)}}`)
  }
  out.push('\\end{center}', '\\vspace{-4pt}')

  // ---- summary
  if (doc.summary.trim()) {
    out.push('', '\\section{Summary}', `\\resumeSummary{${e(doc.summary)}}`)
  }

  // ---- skills
  const skills = doc.skills.filter((skill) => nonEmpty(skill.items).length > 0)
  if (skills.length > 0) {
    out.push('', '\\section{Technical Skills}', '\\resumeSkillListStart')
    for (const skill of skills) {
      const category = skill.category.replace(/:\s*$/, '').trim()
      const label = category ? `\\textbf{${e(category)}:} ` : ''
      out.push(`    \\skillLine{${label}${nonEmpty(skill.items).map(e).join(', ')}}`)
    }
    out.push('\\resumeSkillListEnd')
  }

  // ---- experience
  const jobs = doc.experience.filter((job) => job.company.trim() || job.role.trim())
  if (jobs.length > 0) {
    out.push('', '\\section{Experience}', '\\resumeSubHeadingListStart')
    for (const job of jobs) {
      const groups = job.groups.flatMap((group) => {
        const bullets = bulletItems(group.bullets)
        return group.title.trim() || bullets.length > 0
          ? [`\\resumeGroupHeading{${e(group.title)}}`, ...bullets]
          : []
      })
      out.push(
        '',
        '    \\resumeSubheading',
        `      {${e(job.company)}}{${e(job.dates)}}`,
        `      {${e(job.role)}}{${e(job.location)}}`,
        ...itemList([...bulletItems(job.bullets), ...groups])
      )
    }
    out.push('\\resumeSubHeadingListEnd')
  }

  // ---- projects
  const projects = doc.projects.filter((project) => project.name.trim())
  if (projects.length > 0) {
    out.push('', '\\section{Projects}', '\\resumeSubHeadingListStart')
    for (const project of projects) {
      const title = `\\textbf{${link(project.url, e(project.name))}}`
      const stack = project.stack.trim() ? ` $|$ \\emph{${e(project.stack)}}` : ''
      out.push(
        '',
        '    \\resumeProjectHeading',
        `      {${title}${stack}}{${e(project.dates)}}`,
        ...itemList(bulletItems(project.bullets))
      )
    }
    out.push('\\resumeSubHeadingListEnd')
  }

  // ---- education
  const schools = doc.education.filter((school) => school.school.trim())
  if (schools.length > 0) {
    out.push('', '\\section{Education}', '\\resumeSubHeadingListStart')
    for (const school of schools) {
      out.push(
        '',
        '    \\resumeSubheading',
        `      {${e(school.school)}}{${e(school.dates)}}`,
        `      {${e(school.degree)}}{${e(school.location)}}`,
        ...itemList(bulletItems(school.details))
      )
    }
    out.push('\\resumeSubHeadingListEnd')
  }

  // ---- everything else
  for (const section of doc.sections) {
    const sectionLines = nonEmpty(section.lines)
    if (!section.title.trim() || sectionLines.length === 0) continue
    out.push(
      '',
      `\\section{${e(section.title)}}`,
      '\\resumeSkillListStart',
      ...sectionLines.map((line) => `    \\skillLine{${e(line)}}`),
      '\\resumeSkillListEnd'
    )
  }

  out.push('', '\\end{document}', '')
  return out.join('\n')
}
