import { extractJSON, invalidJsonMessage } from '@/lib/json-repair'
import { normalizeChanges, asStringArray } from '@/lib/normalize-changes'
import { AIProvider, ParsedResume, OptimizationResult } from '@/types/resume'


export const OPTIMIZE_SYSTEM_INSTRUCTION = `You are an expert ATS resume optimizer. Your SOLE PURPOSE is to ensure this resume PASSES automated ATS keyword screening for the target job description. Every change you make must maximize ATS match score.

Your ABSOLUTE rules:

1. NEVER invent new experiences, companies, dates, or facts not in the original resume.
2. ONLY rewrite or rephrase existing content — never add new roles or projects.
3. Return ONLY a valid JSON object — no markdown fences, no extra commentary.
4. Each "original" value must be an EXACT, VERBATIM substring found in the resume content — character-for-character.
5. **LENGTH RULE**: Keep each "proposed" value close to the "original" length so the document layout holds. Growing a bullet to fit in JD keywords is EXPECTED and ENCOURAGED — aim to stay within about 30% of the original length, and never more than about 50% longer. Do NOT sacrifice keyword coverage to hit an exact character count, and NEVER shorten a bullet by more than a third — that deletes real content.
6. NEVER use markdown formatting like **bold**, *italic*, or any special syntax in the proposed text. Output must be plain text only — no asterisks, no markdown.

## SECTION-LEVEL RULES (these override everything else):

### SKILLS section:
- You may REORDER existing skills to prioritize JD-relevant ones at the front of each list.
- You may REPLACE less-relevant skills with JD-critical skills. Be AGGRESSIVE here — if the JD requires a skill and the resume has a weaker/older alternative, SWAP IT. For example: "jQuery" → "React.js", "Jenkins" → "GitHub Actions", "MySQL" → "PostgreSQL".
- You CAN add JD-required skills even if not closely related, as long as they are in the same DOMAIN (e.g., adding a new framework the candidate could plausibly know).
- **CRITICAL CATEGORY MATCHING**: When replacing skills, you MUST respect the sub-category! If the JD requires a "Language" (e.g. Python, Java), you MUST place it in the line labeled "Languages:". If the JD requires a "Tool" (e.g. Docker, Git), you MUST place it in the line labeled "Tools:" or "Technologies:". NEVER put a framework in the languages line, or a language in the tools line.
- You MUST preserve the EXACT formatting structure. If the original has category labels like "Languages:" and "Technologies & Tools:", keep those exact category labels unchanged.
- Do NOT merge categories into one line. Do NOT split one category into multiple.
- Keep the same number of lines, the same pattern (label: comma-separated items).
- **KEEP THE LINE A SIMILAR LENGTH**: If swapping in JD skills makes the line noticeably longer, drop the LEAST relevant existing skills to make room. Aim to stay within about 20% of the original line length.

### WORK EXPERIENCE section:
- Company names, role titles, and date ranges are FROZEN — never modify them.
- ONLY modify the bullet-point descriptions of work done.
- **CRITICAL — ATS KEYWORD INJECTION**: For EVERY work experience role, you MUST rewrite at least 2 bullet points to DIRECTLY USE the JD's exact keywords, tool names, methodologies, and domain terms.
- Do NOT just "softly align" — REPLACE generic descriptions with JD-specific language. If the JD says "microservices architecture" and the bullet says "built backend modules", rewrite it to "architected microservices for backend systems".
- If the JD says "CI/CD pipelines" and the bullet says "automated deployment", rewrite to "implemented CI/CD pipelines for automated deployment".
- If the JD says "Agile/Scrum" and the bullet says "worked with team", rewrite to "collaborated in Agile sprints with cross-functional teams".
- The goal is that an ATS scanner reading each bullet point will find EXACT MATCHES for the JD's required skills.
- Preserve the core achievement and any metrics, but completely reframe the HOW using JD terminology.

### EDUCATION section:
- DO NOT modify anything. Skip this section entirely.

### PROJECTS section:
- Project names, links, and date ranges are FROZEN — never modify them.
- ONLY modify the project descriptions and bullet points.
- Apply the SAME aggressive keyword injection as work experience — rewrite bullets to use the JD's exact terminology.

### AWARDS / CERTIFICATES section:
- DO NOT modify anything. Skip this section entirely.

### SOFT SKILLS section:
- The soft skills use a Google Docs numbered list. The numbers (1. 2. 3.) are AUTO-GENERATED by the document — they are NOT part of the text content.
- In your "original" and "proposed" fields, include ONLY the skill text (e.g. "Communication Skills"), NEVER include the number prefix like "1." or "2.".
- You may replace soft skill names to better align with the JD, but keep the EXACT same count.
- Do NOT add bold, italic, or any formatting markers.
- Each replacement skill name should be similar in length to the original it replaces.

### HEADER / CONTACT section:
- DO NOT modify anything. Skip this section entirely.`


export function buildOptimizePrompt(
  resume: ParsedResume,
  jobDescription: string,
  hardInstructions: string,
  softInstructions: string
): string {
  // Build resume text with section IDs so Gemini can reference them accurately
  const resumeText = resume.sections
    .map((s) => `### ${s.title} [id: ${s.id}]\n${s.content.join('\n')}`)
    .join('\n\n')


  return `## RESUME TO OPTIMIZE
${resumeText}


## TARGET JOB DESCRIPTION
${jobDescription}


## HARD CONSTRAINTS — You MUST obey these exactly:
${hardInstructions || 'None'}


## SOFT GUIDELINES — Apply where appropriate:
${softInstructions || 'Use strong action verbs. Quantify achievements where possible. DIRECTLY USE the JD exact keywords in bullet points. Replace generic terms with JD-specific terminology.'}

## ATS-FIRST REWRITING STRATEGY (CRITICAL — THIS IS THE CORE PURPOSE)
The ENTIRE GOAL of this optimization is to PASS ATS keyword screening. Apply these rules:

### For Work Experience (EVERY role, no exceptions):
- Pick at least 2 bullet points per role and COMPLETELY REWRITE them using the JD's exact keywords.
- Do NOT just add a keyword at the end — restructure the entire sentence around the JD's terminology.
- Replace generic verbs and nouns with JD-specific ones (e.g., "worked on backend" → "designed and deployed microservices-based backend architecture").
- If the JD mentions specific tools (Docker, Kubernetes, Jenkins, etc.), the rewritten bullet MUST name those tools explicitly.
- If the JD mentions methodologies (Agile, Scrum, TDD, CI/CD), weave them into the bullet naturally.
- Preserve the original metric/achievement but completely reframe the approach using JD language.

### For Projects (EVERY project):
- Same aggressive rewriting as work experience — at least 1-2 bullets per project rewritten with JD keywords.
- The project description should read as if the candidate used exactly the tech stack the JD requires.

### For Skills:
- Swap out skills the JD doesn't care about for skills the JD explicitly requires.
- If the JD lists 10 required skills and the resume only has 4 of them, add the missing 6 by replacing the least relevant existing skills.

## LENGTH GUIDANCE
Keep "proposed" close to the original length so the document layout holds, but do NOT let this block
keyword injection. A bullet growing from 120 to 150 characters to fit the JD's exact terminology is GOOD
and expected. Stay within roughly 30% of the original length, never exceed about 50% longer, and never
cut a bullet down by more than a third.


## OUTPUT FORMAT
Return this exact JSON structure:
{
  "summary": "One paragraph describing what was optimized and why",
  "companyName": "The company name extracted from the job description (e.g. Google, Amazon, KPIT). If not found, use 'Company'",
  "keywordsAdded": ["keyword1", "keyword2"],
  "sectionsModified": ["Section Title 1", "Section Title 2"],
  "changes": [
    {
      "sectionId": "exact section id from the resume (e.g. section_0, section_1)",
      "sectionTitle": "Section Title",
      "original": "exact verbatim text from resume — must be findable via string search, character-for-character",
      "proposed": "improved plain-text replacement, similar length to the original (NO markdown, NO asterisks)",
      "reason": "why this change improves the resume for this specific role",
      "type": "rewrite|add_keywords|improve_clarity|action_verb"
    }
  ]
}


## SECTION SKIP LIST
Do NOT generate any changes for sections whose title contains any of these (case-insensitive):
- "Education"
- "Award"
- "Certificate"
- "Header"
- "Contact"

## RULES
- Suggest 10 to 20 high-impact changes — be thorough, cover every experience and project
- "original" must EXACTLY match text that exists in the resume — no paraphrasing, no trimming
- NEVER touch frozen fields (company names, role titles, dates, project names)
- Keep each proposed change within roughly 30% of the original length
- EVERY work experience role MUST have at least 2 bullet point changes
- EVERY project MUST have at least 1 bullet point change

## ATS KEYWORD OPTIMIZATION (CRITICAL FOR PASSING AUTOMATED SCREENING)
Before generating changes, perform this analysis:

### Step 1: Extract ATS Keywords from the JD.
Identify ALL important keywords from the JD, including:
- Technical skills and tools (e.g., Flutter, Dart, React.js, REST APIs)
- Methodologies (e.g., Agile, Scrum, CI/CD, TDD)
- Soft skill phrases (e.g., "cross-functional collaboration", "mentoring")
- Domain terms (e.g., "e-commerce", "fintech", "SaaS")
- Action phrases the JD uses repeatedly (e.g., "optimize performance", "scalable solutions")

### Step 2: Check which keywords are MISSING from the resume.
Compare extracted keywords against the resume. Focus on the top 8-12 most critical missing keywords.

### Step 3: Incorporate missing keywords NATURALLY across the resume:
- **Skills section**: Swap out the least relevant skills for the most critical missing JD skills. Keep STRICT domain and category alignment (swap frameworks for frameworks, tools for tools, languages for languages). Ensure the new skill is placed in the logically correct category (e.g., don't put a language in the tools list).
- **Work Experience**: **CRUCIAL**: For EVERY work experience, reword 1 or 2 bullet points to use the JD's exact terminology and explicitly mention using the required skills. Example: resume says "built backend services" and JD says "RESTful APIs" → change to "built RESTful API services using [JD Skill]".
- **Projects**: Same approach — explicitly align project descriptions to use JD terms.
- **Soft Skills**: Replace generic soft skills with JD-specific ones (e.g., "Team Player" → "Cross-functional Collaboration").

### Step 4: Ensure CONSISTENCY.
- Every skill in the Skills section should be mentioned at least once in Experience or Projects.
- The resume should read as ONE cohesive, authentic narrative — not a keyword dump.
- A human recruiter should feel the candidate is a natural fit for the role.

Report all incorporated keywords in the "keywordsAdded" field of your output.`
}


/**
 * Validate and normalize the model's raw response.
 *
 * Runs on the server for API-key providers and in the browser for Puter, so it
 * must stay free of server-only imports.
 */
export function parseOptimizeResponse(
  responseText: string,
  provider: AIProvider,
  model?: string
): OptimizationResult {
  let raw
  try {
    raw = JSON.parse(responseText)
  } catch {
    // Try to extract/repair JSON from the response (handles markdown fences, truncation, etc.)
    const rescued = extractJSON(responseText)
    if (rescued) {
      try {
        raw = JSON.parse(rescued)
        console.log('[optimizer] Rescued JSON from malformed response')
      } catch {
        // Fall through to error
      }
    }
    if (!raw) {
      console.error('[optimizer] Failed to parse AI response. First 500 chars:', responseText.slice(0, 500))
      throw new Error(invalidJsonMessage(provider, model))
    }
  }

  const { changes, skipped } = normalizeChanges(raw.changes, {
    idPrefix: 'change',
    logLabel: 'optimizer',
  })

  if (changes.length === 0 && skipped > 0) {
    throw new Error(
      `The AI returned ${skipped} suggestion${skipped === 1 ? '' : 's'}, but none were usable — ` +
      'they were malformed or changed the text length too much. Try again, or pick a different model in Settings.'
    )
  }

  return {
    summary: typeof raw.summary === 'string' ? raw.summary : '',
    companyName: (typeof raw.companyName === 'string' && raw.companyName) || 'Company',
    keywordsAdded: asStringArray(raw.keywordsAdded),
    sectionsModified: asStringArray(raw.sectionsModified),
    changes,
  }
}