import { GoogleGenerativeAI } from '@google/generative-ai'
import { ParsedResume, ResumeChange, OptimizationResult } from '@/types/resume'


const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!)


const SYSTEM_INSTRUCTION = `You are an expert ATS resume optimizer. Your ABSOLUTE rules:

1. NEVER invent new experiences, companies, dates, or facts not in the original resume.
2. ONLY rewrite or rephrase existing content — never add new roles or projects.
3. Return ONLY a valid JSON object — no markdown fences, no extra commentary.
4. Each "original" value must be an EXACT, VERBATIM substring found in the resume content — character-for-character.
5. **CRITICAL — SAME LENGTH RULE**: Each "proposed" value MUST have the EXACT same character count as the "original" value (±3 chars max). Count the characters before outputting. If the proposed text is shorter, pad with natural filler words. If longer, trim or rephrase to fit. This is essential to preserve document alignment and formatting.
6. NEVER use markdown formatting like **bold**, *italic*, or any special syntax in the proposed text. Output must be plain text only — no asterisks, no markdown.

## SECTION-LEVEL RULES (these override everything else):

### SKILLS section:
- You may REORDER existing skills to prioritize JD-relevant ones at the front of each list.
- You may REPLACE less-relevant skills with JD-critical skills that are closely related to the candidate's actual tech stack. For example, if the resume lists "jQuery" and the JD needs "React.js", you may swap it.
- NEVER add skills that are completely unrelated to anything in the resume. Only swap within the same domain (e.g., one JS framework for another, one cloud provider for another).
- You MUST preserve the EXACT formatting structure. If the original has category labels like "Languages:" and "Technologies & Tools:", keep those exact category labels unchanged.
- Do NOT merge categories into one line. Do NOT split one category into multiple.
- Keep the same number of lines, the same pattern (label: comma-separated items).
- The total character count per line MUST stay within ±3 chars of the original.

### WORK EXPERIENCE section:
- Company names, role titles, and date ranges are FROZEN — never modify them.
- ONLY modify the bullet-point descriptions of work done.
- Make the descriptions read as if the candidate naturally used the technologies mentioned in the JD — do this softly, do not force-fit.
- Preserve factual accuracy. Do not change what was accomplished, only how it is phrased.

### EDUCATION section:
- DO NOT modify anything. Skip this section entirely.

### PROJECTS section:
- Project names, links, and date ranges are FROZEN — never modify them.
- ONLY modify the project descriptions and bullet points.
- Softly align the descriptions to the JD technologies — same approach as work experience.

### AWARDS / CERTIFICATES section:
- DO NOT modify anything. Skip this section entirely.

### SOFT SKILLS section:
- The soft skills use a Google Docs numbered list. The numbers (1. 2. 3.) are AUTO-GENERATED by the document — they are NOT part of the text content.
- In your "original" and "proposed" fields, include ONLY the skill text (e.g. "Communication Skills"), NEVER include the number prefix like "1." or "2.".
- You may replace soft skill names to better align with the JD, but keep the EXACT same count.
- Do NOT add bold, italic, or any formatting markers.
- Each replacement skill name must be similar in character length to the original it replaces.

### HEADER / CONTACT section:
- DO NOT modify anything. Skip this section entirely.`


function buildPrompt(
  resume: ParsedResume,
  jobDescription: string,
  hardInstructions: string,
  softInstructions: string
): string {
  // Build resume text with section IDs so Gemini can reference them accurately
  const resumeText = resume.sections
    .map((s) => `### ${s.title} [id: ${s.id}]\n${s.content.join('\n')}`)
    .join('\n\n')


  return `## RESUME TO OPTIMIZE
${resumeText}


## TARGET JOB DESCRIPTION
${jobDescription}


## HARD CONSTRAINTS — You MUST obey these exactly:
${hardInstructions || 'None'}


## SOFT GUIDELINES — Apply where appropriate:
${softInstructions || 'Use strong action verbs. Quantify achievements where possible. Align phrasing with keywords from the job description. Improve conciseness and clarity.'}

## JD REFLECTION IN EXPERIENCE & PROJECTS (IMPORTANT)
The job description requirements should SOFTLY reflect in Work Experience and Project descriptions:
- Reframe existing accomplishments using terminology from the JD. Do NOT invent new achievements.
- If the JD mentions "cross-platform mobile development" and the resume says "built a mobile app", reword it to "built a cross-platform mobile application".
- If the JD mentions "RESTful APIs" and the resume says "integrated backend services", reword to "integrated RESTful API services".
- The goal is to make it look like the candidate's existing work naturally aligns with the JD — NOT to fabricate experience.
- Be SUBTLE. A recruiter reading the resume should feel the candidate is a natural fit, not that keywords were force-injected.
- Keep the candidate's authentic voice and real accomplishments intact.


## CRITICAL LENGTH RULE
For every change, the "proposed" text MUST have the EXACT same character count as the "original" text (±3 chars max).
Count carefully. If original is 120 characters, proposed must be 117-123 characters.
This is non-negotiable — the document formatting will break otherwise.


## OUTPUT FORMAT
Return this exact JSON structure:
{
  "summary": "One paragraph describing what was optimized and why",
  "companyName": "The company name extracted from the job description (e.g. Google, Amazon, KPIT). If not found, use 'Company'",
  "keywordsAdded": ["keyword1", "keyword2"],
  "sectionsModified": ["Section Title 1", "Section Title 2"],
  "changes": [
    {
      "sectionId": "exact section id from the resume (e.g. section_0, section_1)",
      "sectionTitle": "Section Title",
      "original": "exact verbatim text from resume — must be findable via string search, character-for-character",
      "proposed": "improved plain-text replacement (MUST be within ±3 chars of original length, NO markdown, NO asterisks)",
      "reason": "why this change improves the resume for this specific role",
      "type": "rewrite|add_keywords|improve_clarity|action_verb"
    }
  ]
}


## SECTION SKIP LIST
Do NOT generate any changes for sections whose title contains any of these (case-insensitive):
- "Education"
- "Award"
- "Certificate"
- "Header"
- "Contact"

## RULES
- Suggest 8 to 15 high-impact changes only
- "original" must EXACTLY match text that exists in the resume — no paraphrasing, no trimming
- NEVER touch frozen fields (company names, role titles, dates, project names)
- Maintain the same character length (±3 chars) for every proposed change

## ATS KEYWORD OPTIMIZATION (CRITICAL FOR PASSING AUTOMATED SCREENING)
Before generating changes, perform this analysis:

### Step 1: Extract ATS Keywords from the JD.
Identify ALL important keywords from the JD, including:
- Technical skills and tools (e.g., Flutter, Dart, React.js, REST APIs)
- Methodologies (e.g., Agile, Scrum, CI/CD, TDD)
- Soft skill phrases (e.g., "cross-functional collaboration", "mentoring")
- Domain terms (e.g., "e-commerce", "fintech", "SaaS")
- Action phrases the JD uses repeatedly (e.g., "optimize performance", "scalable solutions")

### Step 2: Check which keywords are MISSING from the resume.
Compare extracted keywords against the resume. Focus on the top 8-12 most critical missing keywords.

### Step 3: Incorporate missing keywords NATURALLY across the resume:
- **Skills section**: Swap out the least relevant skills for the most critical missing JD skills. Keep domain alignment (swap frameworks for frameworks, tools for tools).
- **Work Experience**: Reword bullet points to use the JD's exact terminology where it fits. Example: resume says "built backend services" and JD says "RESTful APIs" → change to "built RESTful API services".
- **Projects**: Same approach — subtly align project descriptions to use JD terms.
- **Soft Skills**: Replace generic soft skills with JD-specific ones (e.g., "Team Player" → "Cross-functional Collaboration").

### Step 4: Ensure CONSISTENCY.
- Every skill in the Skills section should be mentioned at least once in Experience or Projects.
- The resume should read as ONE cohesive, authentic narrative — not a keyword dump.
- A human recruiter should feel the candidate is a natural fit for the role.

Report all incorporated keywords in the "keywordsAdded" field of your output.`
}


export async function optimizeResume(
  resume: ParsedResume,
  jobDescription: string,
  hardInstructions: string,
  softInstructions: string
): Promise<OptimizationResult> {
  // ✅ Use gemini-2.5-pro — best reasoning quality for resume optimization
  const model = genAI.getGenerativeModel({
    model: 'gemini-2.5-pro',
    systemInstruction: SYSTEM_INSTRUCTION,
    generationConfig: {
      responseMimeType: 'application/json',
      temperature: 0.2,
    },
  })


  const prompt = buildPrompt(resume, jobDescription, hardInstructions, softInstructions)
  const result = await model.generateContent(prompt)
  const raw = JSON.parse(result.response.text())

  const MAX_CHAR_DIFF = 5 // hard limit — reject changes that exceed this

  const changes: ResumeChange[] = (raw.changes ?? [])
    .map(
      (c: Omit<ResumeChange, 'id' | 'approved'>, i: number) => ({
        id: `change_${i}_${Date.now()}`,
        sectionId: c.sectionId,
        sectionTitle: c.sectionTitle,
        original: c.original,
        proposed: c.proposed,
        reason: c.reason,
        type: c.type ?? 'rewrite',
        approved: null,
      })
    )
    .filter((c: ResumeChange) => {
      const diff = Math.abs(c.proposed.length - c.original.length)
      if (diff > MAX_CHAR_DIFF) {
        console.warn(
          `[optimizer] Rejected change (±${diff} chars): "${c.original.slice(0, 50)}..." → "${c.proposed.slice(0, 50)}..."`
        )
        return false
      }
      return true
    })


  return {
    summary: raw.summary ?? '',
    companyName: raw.companyName || 'Company',
    keywordsAdded: raw.keywordsAdded ?? [],
    sectionsModified: raw.sectionsModified ?? [],
    changes,
  }
}