import { GoogleGenerativeAI } from '@google/generative-ai'
import { ParsedResume, ResumeChange, OptimizationResult } from '@/types/resume'


const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY!)


const SYSTEM_INSTRUCTION = `You are an expert ATS resume optimizer. Your ABSOLUTE rules:

1. NEVER invent new experiences, companies, dates, or facts not in the original resume.
2. ONLY rewrite or rephrase existing content — never add new roles or projects.
3. Return ONLY a valid JSON object — no markdown fences, no extra commentary.
4. Each "original" value must be an EXACT, VERBATIM substring found in the resume content — character-for-character.
5. **CRITICAL — SAME LENGTH RULE**: Each "proposed" value MUST have the EXACT same character count as the "original" value (±3 chars max). Count the characters before outputting. If the proposed text is shorter, pad with natural filler words. If longer, trim or rephrase to fit. This is essential to preserve document alignment and formatting.
6. NEVER use markdown formatting like **bold**, *italic*, or any special syntax in the proposed text. Output must be plain text only — no asterisks, no markdown.

## SECTION-LEVEL RULES (these override everything else):

### SKILLS section:
- You may ONLY reorder the existing skills to prioritize JD-relevant ones at the front of each list.
- NEVER add a skill that does not already exist in the original resume. NEVER remove an existing skill.
- You MUST preserve the EXACT formatting structure. If the original has category labels like "Languages:" and "Technologies & Tools:", keep those exact category labels unchanged.
- Do NOT merge categories into one line. Do NOT split one category into multiple.
- Keep the same number of lines, the same pattern (label: comma-separated items), and the EXACT same set of skill items — only the order may change.
- Do NOT rename skills (e.g. do not change "Java" to "Java 17", do not change "CI/CD Tools" to "CI/CD").

### WORK EXPERIENCE section:
- Company names, role titles, and date ranges are FROZEN — never modify them.
- ONLY modify the bullet-point descriptions of work done.
- Make the descriptions read as if the candidate naturally used the technologies mentioned in the JD — do this softly, do not force-fit.
- Preserve factual accuracy. Do not change what was accomplished, only how it is phrased.

### EDUCATION section:
- DO NOT modify anything. Skip this section entirely.

### PROJECTS section:
- Project names, links, and date ranges are FROZEN — never modify them.
- ONLY modify the project descriptions and bullet points.
- Softly align the descriptions to the JD technologies — same approach as work experience.

### AWARDS / CERTIFICATES section:
- DO NOT modify anything. Skip this section entirely.

### SOFT SKILLS section:
- The soft skills use a Google Docs numbered list. The numbers (1. 2. 3.) are AUTO-GENERATED by the document — they are NOT part of the text content.
- In your "original" and "proposed" fields, include ONLY the skill text (e.g. "Communication Skills"), NEVER include the number prefix like "1." or "2.".
- You may replace soft skill names to better align with the JD, but keep the EXACT same count.
- Do NOT add bold, italic, or any formatting markers.
- Each replacement skill name must be similar in character length to the original it replaces.

### HEADER / CONTACT section:
- DO NOT modify anything. Skip this section entirely.`


function buildPrompt(
  resume: ParsedResume,
  jobDescription: string,
  hardInstructions: string,
  softInstructions: string
): string {
  // Build resume text with section IDs so Gemini can reference them accurately
  const resumeText = resume.sections
    .map((s) => `### ${s.title} [id: ${s.id}]\n${s.content.join('\n')}`)
    .join('\n\n')


  return `## RESUME TO OPTIMIZE
${resumeText}


## TARGET JOB DESCRIPTION
${jobDescription}


## HARD CONSTRAINTS — You MUST obey these exactly:
${hardInstructions || 'None'}


## SOFT GUIDELINES — Apply where appropriate:
${softInstructions || 'Use strong action verbs. Quantify achievements where possible. Align phrasing with keywords from the job description. Improve conciseness and clarity.'}


## CRITICAL LENGTH RULE
For every change, the "proposed" text MUST have the EXACT same character count as the "original" text (±3 chars max).
Count carefully. If original is 120 characters, proposed must be 117-123 characters.
This is non-negotiable — the document formatting will break otherwise.


## OUTPUT FORMAT
Return this exact JSON structure:
{
  "summary": "One paragraph describing what was optimized and why",
  "companyName": "The company name extracted from the job description (e.g. Google, Amazon, KPIT). If not found, use 'Company'",
  "keywordsAdded": ["keyword1", "keyword2"],
  "sectionsModified": ["Section Title 1", "Section Title 2"],
  "changes": [
    {
      "sectionId": "exact section id from the resume (e.g. section_0, section_1)",
      "sectionTitle": "Section Title",
      "original": "exact verbatim text from resume — must be findable via string search, character-for-character",
      "proposed": "improved plain-text replacement (MUST be within ±3 chars of original length, NO markdown, NO asterisks)",
      "reason": "why this change improves the resume for this specific role",
      "type": "rewrite|add_keywords|improve_clarity|action_verb"
    }
  ]
}


## SECTION SKIP LIST
Do NOT generate any changes for sections whose title contains any of these (case-insensitive):
- "Education"
- "Award"
- "Certificate"
- "Header"
- "Contact"

## RULES
- Suggest 8 to 15 high-impact changes only
- "original" must EXACTLY match text that exists in the resume — no paraphrasing, no trimming
- NEVER touch frozen fields (company names, role titles, dates, project names)
- Maintain the same character length (±3 chars) for every proposed change`
}


export async function optimizeResume(
  resume: ParsedResume,
  jobDescription: string,
  hardInstructions: string,
  softInstructions: string
): Promise<OptimizationResult> {
  // ✅ Use gemini-2.5-pro — best reasoning quality for resume optimization
  const model = genAI.getGenerativeModel({
    model: 'gemini-2.5-pro',
    systemInstruction: SYSTEM_INSTRUCTION,
    generationConfig: {
      responseMimeType: 'application/json',
      temperature: 0.2,
    },
  })


  const prompt = buildPrompt(resume, jobDescription, hardInstructions, softInstructions)
  const result = await model.generateContent(prompt)
  const raw = JSON.parse(result.response.text())


  const changes: ResumeChange[] = (raw.changes ?? []).map(
    (c: Omit<ResumeChange, 'id' | 'approved'>, i: number) => ({
      id: `change_${i}_${Date.now()}`,
      sectionId: c.sectionId,
      sectionTitle: c.sectionTitle,
      original: c.original,
      proposed: c.proposed,
      reason: c.reason,
      type: c.type ?? 'rewrite',
      approved: null,
    })
  )


  return {
    summary: raw.summary ?? '',
    companyName: raw.companyName || 'Company',
    keywordsAdded: raw.keywordsAdded ?? [],
    sectionsModified: raw.sectionsModified ?? [],
    changes,
  }
}